#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..', '..');
const generatedDir = path.resolve(
  repoRoot,
  'src',
  'optimizer',
  'wasm',
  'generated',
);
const wasmPath = path.resolve(generatedDir, 'craftbuddy_engine_bg.wasm');
const gluePath = path.resolve(generatedDir, 'craftbuddy_engine.js');
const outputPath = path.resolve(generatedDir, 'craftbuddy_engine_inline.js');
const dtsPath = path.resolve(generatedDir, 'craftbuddy_engine_inline.d.ts');

if (!fs.existsSync(wasmPath)) {
  throw new Error(`WASM binary not found: ${wasmPath}`);
}

if (!fs.existsSync(gluePath)) {
  throw new Error(`wasm-bindgen glue not found: ${gluePath}`);
}

const rawGlue = fs.readFileSync(gluePath, 'utf8');
const asyncFallbackPatch =
  "throw new Error('CraftBuddy uses inline WASM initSync; async WASM URL loading is disabled.');";
const patchedGlue = rawGlue.replace(
  "module_or_path = new URL('craftbuddy_engine_bg.wasm', import.meta.url);",
  asyncFallbackPatch,
);
if (patchedGlue === rawGlue && !rawGlue.includes(asyncFallbackPatch)) {
  throw new Error('Unable to patch wasm-bindgen async URL fallback.');
}
fs.writeFileSync(gluePath, patchedGlue);

const wasmBase64 = fs.readFileSync(wasmPath).toString('base64');

fs.writeFileSync(
  outputPath,
  `/* Generated by scripts/wasm/inline-wasm.js. Do not edit. */
import { initSync, runMcts as wasmRunMcts } from './craftbuddy_engine.js';

const WASM_BASE64 = '${wasmBase64}';
let initialized = false;

function decodeBase64ToBytes(value) {
  if (typeof atob === 'function') {
    const binary = atob(value);
    const bytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index += 1) {
      bytes[index] = binary.charCodeAt(index);
    }
    return bytes;
  }

  if (typeof Buffer !== 'undefined') {
    return Uint8Array.from(Buffer.from(value, 'base64'));
  }

  throw new Error('No base64 decoder available for CraftBuddy WASM engine.');
}

function ensureInitialized() {
  if (initialized) return;
  initSync({ module: decodeBase64ToBytes(WASM_BASE64) });
  initialized = true;
}

export function runMcts(input) {
  ensureInitialized();
  return wasmRunMcts(input);
}
`,
);

fs.writeFileSync(
  dtsPath,
  `export function runMcts(input: unknown): unknown;
`,
);

console.log(`Wrote inline WASM module: ${path.relative(repoRoot, outputPath)}`);
